services:
  postgresdb:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: drizzle_29_March
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
